Vue.use(VueLazyload,{preLoad:1,loading:siteWeb.basePath+"skins/imgs/jsj/load-img.png"});
var message=function(a){a?$(".page-loading").show():$(".page-loading").hide()},toolVue=new Vue({el:"#app",data:function(){return{topActiveMenu:"designTool",restaurants:[],searchImg:"",sideActiveMenu:"useful",designToolList:[],previewList:"常用推荐",designSearchToolList:[],recogImage:"",recogText:"",compareList:[],previewVisible:!1,searchVal:"",downSwitch:!0,isMulti:!1,searchEnd:!1,designPreviewImg:"",printPreviewImg:"",textType:"1"}},beforeCreate:function(){window.parent.indexVue.isPrintTmpl=!1;window.parent.indexVue.isNotHomePage=
!1},created:function(){this.getDesignToll();document.addEventListener("paste",function(a){if(-1!=$(".tem-main-title").text().indexOf("识别"))toolVue.onPaste(a)})},watch:{textType:function(a){this.emptyOcrText()}},methods:{goToHelp:function(){window.location.href=siteWeb.basePath+"jsj/help.do"},getDesignToll:function(){var a=this;$.ajaxPromise({url:siteWeb.basePath+"/jsj/getDesignTool.do",method:"get"}).then(function(b){a.designToolList=b;a.previewList="常用推荐";a.sideActiveMenu="useful";$("#app").show();
$(".page-loading").hide()}).catch(function(b){$("#app").show();$(".page-loading").hide();a.$message({type:"false",message:"获取资源失败,请联系客服!"})})},entTempCenter:function(a){window.location.href=siteWeb.basePath+"jsj/"+a+".do"},searchToolByKeyWords:function(){var a=this;$.ajaxPromise({url:siteWeb.basePath+"tool/toolSearch.do",method:"POST",contentType:"application/x-www-form-urlencoded",data:{searchWords:this.searchVal}}).then(function(b){a.designSearchToolList=b;a.previewList="designSearchToolList";a.sideActiveMenu=
""}).catch(function(b){a.$message({type:"false",message:"获取资源失败,请联系客服!"})})},callBack:function(a){window.location.href=siteWeb.basePath+"jsj/main/designTool.do?classifyname\x3d"+a},onPaste:function(a){this.recogText=this.recogImage="";a=(a.clipboardData||window.clipboardData).items;var b=null;if(a&&a.length){for(var c=0;c<a.length;c++)if(-1!==a[c].type.indexOf("image")){b=a[c].getAsFile();break}if(b){var e=toolVue.$loading({lock:!0,text:"Loading",spinner:"el-icon-loading",background:"rgba(0, 0, 0, 0.2)"}),
f=new FormData;f.append("file",b);f.append("textType",this.textType);var d=new FileReader;d.onload=function(a){toolVue.recogImage=d.result;$.ajaxPromise({url:siteWeb.basePath+"userCenterJsj/uploadOCR.do",method:"post",data:f,contentType:!1,processData:!1}).then(function(a){toolVue.recogText=a;e.close()}).catch(function(a){console.log("第一个请求失败",a);e.close()})};d.readAsDataURL(b)}else toolVue.$message({type:"false",message:"您未复制内容或复制的内容不是图片！"})}else toolVue.$message({type:"false",message:"暂不支持您的浏览器的图片粘贴操作！"})},
beforeImageUpload:function(a){var b;b="image/jpeg"===a.type||"image/jpg"===a.type||"image/png"===a.type?!0:!1;a=10>a.size/1024/1024;b||this.$message.error("上传文件只能是 JPG/PNG 格式!");a||this.$message.error("上传文件大小不能超过 10MB!");return b&a},handleUploadForm:function(a){var b=this.$loading({lock:!0,text:"Loading",spinner:"el-icon-loading",background:"rgba(0, 0, 0, 0.2)"}),c=new FormData;c.append("file",a.file);c.append("textType",this.textType);var e=new FileReader;e.readAsDataURL(a.file);e.onload=function(a){toolVue.recogImage=
e.result;$.ajaxPromise({url:siteWeb.basePath+"userCenterJsj/uploadOCR.do",method:"post",data:c,contentType:!1,processData:!1}).then(function(a){toolVue.recogText=a;b.close()}).catch(function(a){console.log("第一个请求失败",a);b.close()})}},handleUpload:function(a,b,c){console.log(c)},uploadSuccess:function(a,b,c){console.log(c)},copyOcrText:function(){var a=this.recogText;if("转换的内容在这里"==a)layer.msg("请先上传图片完成识别！",{time:1500});else{var a=a.replace(/<br\/>/g,"\n"),b=document.createElement("textarea");b.value=
a;document.body.appendChild(b);b.select();b.setSelectionRange(0,b.value.length);document.execCommand("Copy");document.body.removeChild(b);this.$message.success("复制成功")}},downloadOcrText:function(){var a=this.recogText,a=a.replace(/<br\/>/g,"\r\n"),b=window.URL||window.webkitURL||window,c=new Blob([a]),a=document.createElementNS("http://www.w3.org/1999/xhtml","a");a.href=b.createObjectURL(c);a.download="智能转换.txt";b=document.createEvent("MouseEvents");b.initMouseEvent("click",!0,!1,window,0,0,0,0,0,
!1,!1,!1,!1,0,null);a.dispatchEvent(b)},emptyOcrText:function(){this.recogImage=this.recogText=""},searchByDesignNo:function(){var a=Utils.trim(this.searchVal);null==a||""==a?this.$message.error("请输入设计单号..."):-1!=a.indexOf("版第")&&-1!=a.indexOf("版)")?this.$message.error("多版设计请使用主订单号编辑..."):$.post(siteWeb.basePath+"tool/imgPreviewSearch.do",{designNo:a,isLikeSearch:"noLikeSearch"},function(b){if(b.success){toolVue.searchEnd=!0;b=b.userData.data;toolVue.compareList=[];for(var c=0;c<b.length;c++){var e=
{},f={},d={};f.title="设计稿第"+Number(c+1)+"页";f.img=siteWeb.basePath+"/assets/resource/imgs/normal/"+b[c].previewImg;d.title="生产稿第"+Number(c+1)+"页";d.img=siteWeb.basePath+"/assets/resource/imgs/normal/"+b[c].productImg;e.design=f;e.print=d;toolVue.compareList.push(e)}-1!=a.indexOf("版)")?toolVue.isMulti=!0:toolVue.isMulti=!1}else toolVue.searchEnd=!1,toolVue.$message.error(b.message),toolVue.downSwitch=!1,-1!=b.message.indexOf("您的设计")?toolVue.downSwitch=!0:""!=$("#designNo").val()&&setTimeout(function(){$(".search-btn").trigger("click")},
7E3)},"json").error(function(){toolVue.$message.error("查询失败")})},editDesign:function(){var a=Utils.trim(this.searchVal);if(""!=a&&-1!=a.indexOf("版第")&&-1!=a.indexOf("版)"))toolVue.$message.error("多版设计请使用主订单号编辑");else{var b=this,a="thirdDesignNo\x3d"+a,c=siteWeb.basePath+"/third/editDesign.do",c=c.replace("siteWeb","diyWeb");$.ajax({async:!1,contentType:"application/x-www-form-urlencoded;charset\x3dutf-8",url:c,data:a,cache:!0,type:"post",dataType:"json",success:function(a){if(0==a.success)toolVue.$message.error(a.message);
else{var c=a.designId;if("tshirt"==$("#diyType").val())$(b).attr("href","tshirt/"+c+"/"+longUserId+"/0/1/tShirtEdit.do");else if(-1!=$(".text-tips").text().indexOf("人像卡")){var d=$("#copyLink").val().split("-"),d=-1!=d[0].indexOf("单圆")?3:-1!=d[0].indexOf("双圆")?2:-1!=d[0].indexOf("长孔")?1:-1!=d[0].indexOf("无孔")?4:1;window.open(siteWeb.basePath.replace("siteWeb","diyWeb")+"/workCard/"+c+"/"+a.longUserId+"/0/1/"+d+"/showDiy2Edit.do","_blank")}else"haslogin"==a.longUserId?window.open(siteWeb.basePath.replace("siteWeb",
"diyWeb")+"/third/"+c+"/1/thirdLoginDiyEdit.do","_blank"):"nologin"==a.longUserId?toolVue.$message.error("编辑此作品需先登录！"):window.open(siteWeb.basePath.replace("siteWeb","diyWeb")+"/third/"+c+"/"+a.longUserId+"/0/1/thirdDiyEdit.do","_blank")}},error:function(){console.log("edit user design goods error")}})}},downloadDesign:function(){var a=Utils.trim(this.searchVal);$.post(siteWeb.basePath.replace("siteWeb","diyWeb")+"/download/pdfDownload.do",{designNo:a},function(a){if(a.result){window.location.href=
a.platform+"/user/downFile.do?token\x3d"+a.data;a={thirdOrderNo:a.designNo,userPhone:a.userPhone};var b=siteWeb.basePath.replace("siteWeb","diyWeb")+"/download/updateDownLoadDetail.do";$.ajax({url:b,data:a,type:"post",dataType:"json",success:function(a){console.log(a.message)},error:function(){console.log(materData.message)}})}else"noLogin"==a.message&&toolVue.$message.error("请先登录！"),"noPermission"==a.message&&toolVue.$message.error("对不起, 您的账号权限不足, 请联系管理员！")})},copyDesign:function(){var a=Utils.trim(this.searchVal);
if(null==a||""==a)this.$message.error("请输入设计单号...");else if(a=Utils.trim(this.searchVal),""!=a&&-1!=a.indexOf("版第")&&-1!=a.indexOf("版)"))toolVue.$message.error("多版设计请使用主订单号复制设计！");else{var b=a.indexOf("-"),b="copy"+a.substr(b,a.length);if(-1!=$(".text-tips").text().indexOf("人像卡")){var a=$("#copyLink").val().split("-"),c;-1!=a[0].indexOf("单圆孔")?c=3:-1!=a[0].indexOf("双圆孔")?c=2:-1!=a[0].indexOf("长孔")?c=1:-1!=a[0].indexOf("无孔")&&(c=4);window.open(siteWeb.basePath.replace("siteWeb","diyWeb")+"/workCard/"+
b+"/"+c+"/thirdDiyCopy.do")}else window.open(siteWeb.basePath.replace("siteWeb","diyWeb")+"/third/thirdDiyCopy.do?designNo\x3d"+a)}},copyDesignNo:function(){var a=Utils.trim(this.searchVal);$("body").append("\x3cinput   id\x3d'designNo' type\x3d'text' /\x3e");var b=document.getElementById("designNo");$("#designNo").val(a);b.select();document.execCommand("Copy");$("#designNo").remove();toolVue.$message.success("已复制到剪贴板！")},copyMultiDesignNo:function(){var a=Utils.trim(this.searchVal);if(""==a||-1==
a.indexOf("版)"))layer.msg('非多版设计单号请使用 "复制设计单号" ');else{for(var b=a.split("(")[0],c=a.split(")")[1],e=a.split("(")[1].split(")")[0],a="",f=Number(e.substring(1,e.length-1)),d=0;d<f;d++)var g=Utils.NumberToChinese(d+1),a=a+(b+"("+e+"第"+g+"版)"+c+"，");a=a.substring(0,a.length-1);$("body").append("\x3cinput   id\x3d'multiArrs' type\x3d'text' /\x3e");b=document.getElementById("multiArrs");$("#multiArrs").val(a);b.select();document.execCommand("Copy");$("#multiArrs").remove();toolVue.$message.success("已复制到剪贴板！")}},
seePreview:function(a,b){this.designPreviewImg=a;this.printPreviewImg=b;this.previewVisible=!0}}});