!function(n,t){"object"==typeof exports&&"undefined"!=typeof module?module.exports=t():"function"==typeof define&&define.amd?define(t):n.ColorThief=t()}(this,function(){if(!n)var n={map:function(a,d){var g={};return d?a.map(function(a,b){return g.index=b,d.call(g,a)}):a.slice()},naturalOrder:function(a,d){return a<d?-1:a>d?1:0},sum:function(a,d){var g={};return a.reduce(d?function(a,b,c){return g.index=c,a+d.call(g,b)}:function(a,b){return a+b},0)},max:function(a,d){return Math.max.apply(null,d?n.map(a,
d):a)}};var t=function(){function a(b){function c(){m.sort(b);a=!0}var m=[],a=!1;return{push:function(c){m.push(c);a=!1},peek:function(b){return a||c(),void 0===b&&(b=m.length-1),m[b]},pop:function(){return a||c(),m.pop()},size:function(){return m.length},map:function(b){return m.map(b)},debug:function(){return a||c(),m}}}function d(b,c,a,d,l,e,h){this.r1=b;this.r2=c;this.g1=a;this.g2=d;this.b1=l;this.b2=e;this.histo=h}function g(){this.vboxes=new a(function(b,c){return n.naturalOrder(b.vbox.count()*
b.vbox.volume(),c.vbox.count()*c.vbox.volume())})}function f(b,c){if(c.count()){var a=c.r2-c.r1+1,d=c.g2-c.g1+1,l=n.max([a,d,c.b2-c.b1+1]);if(1==c.count())return[c.copy()];var e,h,k,f,g=0,q=[],u=[];if(l==a)for(e=c.r1;e<=c.r2;e++){f=0;for(h=c.g1;h<=c.g2;h++)for(k=c.b1;k<=c.b2;k++)f+=b[(e<<10)+(h<<5)+k]||0;q[e]=g+=f}else if(l==d)for(e=c.g1;e<=c.g2;e++){f=0;for(h=c.r1;h<=c.r2;h++)for(k=c.b1;k<=c.b2;k++)f+=b[(h<<10)+(e<<5)+k]||0;q[e]=g+=f}else for(e=c.b1;e<=c.b2;e++){f=0;for(h=c.r1;h<=c.r2;h++)for(k=
c.g1;k<=c.g2;k++)f+=b[(h<<10)+(k<<5)+e]||0;q[e]=g+=f}return q.forEach(function(b,c){u[c]=g-b}),function(b){var a,f,m,d,l=b+"1",k=b+"2";for(e=c[l];e<=c[k];e++)if(q[e]>g/2){b=c.copy();m=c.copy();for(d=(a=e-c[l])<=(f=c[k]-e)?Math.min(c[k]-1,~~(e+f/2)):Math.max(c[l],~~(e-1-a/2));!q[d];)d++;for(a=u[d];!a&&q[d-1];)a=u[--d];return b[k]=d,m[l]=b[k]+1,[b,m]}}(l==a?"r":l==d?"g":"b")}}return d.prototype={volume:function(b){return this._volume&&!b||(this._volume=(this.r2-this.r1+1)*(this.g2-this.g1+1)*(this.b2-
this.b1+1)),this._volume},count:function(b){var c=this.histo;if(!this._count_set||b){var a,d,f=0;for(b=this.r1;b<=this.r2;b++)for(a=this.g1;a<=this.g2;a++)for(d=this.b1;d<=this.b2;d++)f+=c[(b<<10)+(a<<5)+d]||0;this._count=f;this._count_set=!0}return this._count},copy:function(){return new d(this.r1,this.r2,this.g1,this.g2,this.b1,this.b2,this.histo)},avg:function(b){var c=this.histo;if(!this._avg||b){var a,d,f,e=0,h=0,k=0,g=0;for(a=this.r1;a<=this.r2;a++)for(d=this.g1;d<=this.g2;d++)for(f=this.b1;f<=
this.b2;f++)e+=b=c[(a<<10)+(d<<5)+f]||0,h+=b*(a+.5)*8,k+=b*(d+.5)*8,g+=b*(f+.5)*8;this._avg=e?[~~(h/e),~~(k/e),~~(g/e)]:[~~(8*(this.r1+this.r2+1)/2),~~(8*(this.g1+this.g2+1)/2),~~(8*(this.b1+this.b2+1)/2)]}return this._avg},contains:function(b){var c=b[0]>>3;return gval=b[1]>>3,bval=b[2]>>3,c>=this.r1&&c<=this.r2&&gval>=this.g1&&gval<=this.g2&&bval>=this.b1&&bval<=this.b2}},g.prototype={push:function(b){this.vboxes.push({vbox:b,color:b.avg()})},palette:function(){return this.vboxes.map(function(b){return b.color})},
size:function(){return this.vboxes.size()},map:function(b){for(var c=this.vboxes,a=0;a<c.size();a++)if(c.peek(a).vbox.contains(b))return c.peek(a).color;return this.nearest(b)},nearest:function(b){for(var c,a,d,f=this.vboxes,e=0;e<f.size();e++)((a=Math.sqrt(Math.pow(b[0]-f.peek(e).color[0],2)+Math.pow(b[1]-f.peek(e).color[1],2)+Math.pow(b[2]-f.peek(e).color[2],2)))<c||void 0===c)&&(c=a,d=f.peek(e).color);return d},forcebw:function(){var b=this.vboxes;b.sort(function(b,c){return n.naturalOrder(n.sum(b.color),
n.sum(c.color))});var c=b[0].color;5>c[0]&&5>c[1]&&5>c[2]&&(b[0].color=[0,0,0]);var c=b.length-1,a=b[c].color;251<a[0]&&251<a[1]&&251<a[2]&&(b[c].color=[255,255,255])}},{quantize:function(b,c){function m(b,c){for(var a,d=b.size(),e=0;1E3>e&&!(d>=c)&&!(1E3<e++);)if((a=b.pop()).count()){var h=f(p,a);a=h[0];h=h[1];if(!a)break;b.push(a);h&&(b.push(h),d++)}else b.push(a),e++}if(!b.length||2>c||256<c)return!1;var p=function(b){var c,a=Array(32768);return b.forEach(function(b){c=(b[0]>>3<<10)+(b[1]>>3<<
5)+(b[2]>>3);a[c]=(a[c]||0)+1}),a}(b);p.forEach(function(){});var l=function(b,c){var a,f,e,h=1E6,g=0,l=1E6,m=0,n=1E6,p=0;return b.forEach(function(b){(a=b[0]>>3)<h?h=a:a>g&&(g=a);(f=b[1]>>3)<l?l=f:f>m&&(m=f);(e=b[2]>>3)<n?n=e:e>p&&(p=e)}),new d(h,g,l,m,n,p,c)}(b,p);b=new a(function(b,c){return n.naturalOrder(b.count(),c.count())});b.push(l);m(b,.75*c);for(l=new a(function(b,c){return n.naturalOrder(b.count()*b.volume(),c.count()*c.volume())});b.size();)l.push(b.pop());m(l,c);for(c=new g;l.size();)c.push(l.pop());
return c}}}().quantize,v=function(a){this.canvas=document.createElement("canvas");this.context=this.canvas.getContext("2d");this.width=this.canvas.width=a.width;this.height=this.canvas.height=a.height;this.context.drawImage(a,0,0,this.width,this.height)};v.prototype.getImageData=function(){return this.context.getImageData(0,0,this.width,this.height)};var r=function(){};return r.prototype.getColor=function(a,d){return void 0===d&&(d=10),this.getPalette(a,5,d)[0]},r.prototype.getPalette=function(a,
d,g){d=function(a){var b=a.colorCount;a=a.quality;if(void 0!==b&&Number.isInteger(b)){if(1===b)throw Error("colorCount should be between 2 and 20. To get one color, call getColor() instead of getPalette()");b=Math.max(b,2);b=Math.min(b,20)}else b=10;return void 0===a||Number.isInteger(a)?a=10:1>a&&(a=10),{colorCount:b,quality:a}}({colorCount:d,quality:g});a=new v(a);a=function(a,b,c){for(var d=[],f=0,g,e,h,k,n=void 0;f<b;f+=c)e=a[0+(g=4*f)],h=a[g+1],k=a[g+2],(void 0===(n=a[g+3])||125<=n)&&(250<e&&
250<h&&250<k||d.push([e,h,k]));return d}(a.getImageData().data,a.width*a.height,d.quality);return(a=t(a,d.colorCount))?a.palette():null},r.prototype.getColorFromUrl=function(a,d,g){var f=document.createElement("img"),b=this;f.addEventListener("load",function(){var c=b.getPalette(f,5,g);d(c[0],a)});f.src=a},r.prototype.getImageData=function(a,d){var g=new XMLHttpRequest;g.open("GET",a,!0);g.responseType="arraybuffer";g.onload=function(){if(200==this.status){for(var a=new Uint8Array(this.response),
b=a.length,c=Array(b),b=0;b<a.length;b++)c[b]=String.fromCharCode(a[b]);a=c.join("");a=window.btoa(a);d("data:image/png;base64,"+a)}};g.send()},r.prototype.getColorAsync=function(a,d,g){var f=this;this.getImageData(a,function(b){var a=document.createElement("img");a.addEventListener("load",function(){var b=f.getPalette(a,5,g);d(b[0],this)});a.src=b})},r});